name: Cypress Tests
on:
    push:
        branches: [master]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Cypress Run
              uses: cypress-io/github-action@v4.1.0

              with:
                  build: npm run build
                  start: npm start
